// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlQOxgh-YvfbkLg5d99BjcvHTnV-u-AMI',
    appId: '1:47229498694:web:263528c781af183e6de147',
    messagingSenderId: '47229498694',
    projectId: 'untitled-d6348',
    authDomain: 'untitled-d6348.firebaseapp.com',
    storageBucket: 'untitled-d6348.appspot.com',
    measurementId: 'G-KXB58Y2SGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnc9aX7zp067_0pTIppHTXpkaxu-HZ-fM',
    appId: '1:47229498694:android:9de91d46d615763a6de147',
    messagingSenderId: '47229498694',
    projectId: 'untitled-d6348',
    storageBucket: 'untitled-d6348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0Hb_fhv0aEy2V94KE1wjDfDncsDVC1Y',
    appId: '1:47229498694:ios:402904141b6da6b06de147',
    messagingSenderId: '47229498694',
    projectId: 'untitled-d6348',
    storageBucket: 'untitled-d6348.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0Hb_fhv0aEy2V94KE1wjDfDncsDVC1Y',
    appId: '1:47229498694:ios:94ac03e36246c9f96de147',
    messagingSenderId: '47229498694',
    projectId: 'untitled-d6348',
    storageBucket: 'untitled-d6348.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
